/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_raw_marker = 1,
  aux_sym_global_token1 = 2,
  aux_sym_global_token2 = 3,
  anon_sym_DOT = 4,
  sym_format_string = 5,
  anon_sym_LBRACE = 6,
  anon_sym_COLON = 7,
  anon_sym_RBRACE = 8,
  sym__identifier = 9,
  sym_error = 10,
  sym_input = 11,
  sym_qualified = 12,
  sym_global = 13,
  sym_local = 14,
  sym_interpolation = 15,
  aux_sym_global_repeat1 = 16,
  aux_sym_local_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_raw_marker] = "raw_marker",
  [aux_sym_global_token1] = "global_token1",
  [aux_sym_global_token2] = "global_token2",
  [anon_sym_DOT] = ".",
  [sym_format_string] = "format_string",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COLON] = ":",
  [anon_sym_RBRACE] = "}",
  [sym__identifier] = "_identifier",
  [sym_error] = "error",
  [sym_input] = "input",
  [sym_qualified] = "qualified",
  [sym_global] = "global",
  [sym_local] = "local",
  [sym_interpolation] = "interpolation",
  [aux_sym_global_repeat1] = "global_repeat1",
  [aux_sym_local_repeat1] = "local_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_raw_marker] = sym_raw_marker,
  [aux_sym_global_token1] = aux_sym_global_token1,
  [aux_sym_global_token2] = aux_sym_global_token2,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_format_string] = sym_format_string,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__identifier] = sym__identifier,
  [sym_error] = sym_error,
  [sym_input] = sym_input,
  [sym_qualified] = sym_qualified,
  [sym_global] = sym_global,
  [sym_local] = sym_local,
  [sym_interpolation] = sym_interpolation,
  [aux_sym_global_repeat1] = aux_sym_global_repeat1,
  [aux_sym_local_repeat1] = aux_sym_local_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_marker] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_global_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_global_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_format_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_error] = {
    .visible = true,
    .named = true,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified] = {
    .visible = true,
    .named = true,
  },
  [sym_global] = {
    .visible = true,
    .named = true,
  },
  [sym_local] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_global_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_local_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 5,
  [13] = 3,
  [14] = 6,
  [15] = 2,
  [16] = 8,
  [17] = 9,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 21,
  [24] = 24,
  [25] = 18,
  [26] = 20,
  [27] = 22,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 31,
  [33] = 33,
  [34] = 33,
  [35] = 35,
  [36] = 29,
};

static const TSCharacterRange sym_format_string_character_set_4[] = {
  {'.', '.'}, {'0', '9'}, {'X', 'X'}, {'b', 'b'}, {'d', 'd'}, {'f', 'f'}, {'o', 'o'}, {'q', 'q'},
  {'s', 's'}, {'u', 'u'}, {'x', 'x'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == ':') ADVANCE(23);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '}') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        ' ', 1,
        '#', 17,
        '+', 2,
        '-', 4,
        '.', 7,
        '0', 5,
        'q', 13,
        '{', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if ((set_contains(sym_format_string_character_set_4, 11, lookahead)) &&
          (lookahead < '0' || '9' < lookahead)) ADVANCE(21);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '#', 3,
        '-', 4,
        '.', 7,
        '0', 5,
        'q', 13,
        'X', 21,
        'b', 21,
        'd', 21,
        'f', 21,
        'o', 21,
        's', 21,
        'u', 21,
        'x', 21,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '-', 6,
        '.', 10,
        '0', 8,
        'q', 12,
        'X', 21,
        'b', 21,
        'f', 21,
        'o', 21,
        's', 21,
        'x', 21,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '.', 7,
        '0', 5,
        'q', 13,
        'X', 21,
        'b', 21,
        'd', 21,
        'f', 21,
        'o', 21,
        's', 21,
        'u', 21,
        'x', 21,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '.', 7,
        'q', 13,
        'X', 21,
        'b', 21,
        'd', 21,
        'f', 21,
        'o', 21,
        's', 21,
        'u', 21,
        'x', 21,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '.', 10,
        '0', 8,
        'q', 12,
        'X', 21,
        'b', 21,
        'f', 21,
        'o', 21,
        's', 21,
        'x', 21,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '.', 10,
        'q', 13,
        'X', 21,
        'b', 21,
        'd', 21,
        'f', 21,
        'o', 21,
        's', 21,
        'u', 21,
        'x', 21,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        '.', 10,
        'q', 12,
        'X', 21,
        'b', 21,
        'f', 21,
        'o', 21,
        's', 21,
        'x', 21,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      ADVANCE_MAP(
        '.', 10,
        'q', 12,
        'X', 21,
        'b', 21,
        'd', 21,
        'f', 21,
        'o', 21,
        's', 21,
        'u', 21,
        'x', 21,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(21);
      if (lookahead == 'q') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == 'f') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '}') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_raw_marker);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_raw_marker);
      ADVANCE_MAP(
        '-', 6,
        '.', 10,
        '0', 8,
        'q', 12,
        'X', 21,
        'b', 21,
        'f', 21,
        'o', 21,
        's', 21,
        'x', 21,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_global_token1);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_global_token2);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_format_string);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 1, .external_lex_state = 2},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 1, .external_lex_state = 2},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 14},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 14},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 14},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 14},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_raw_marker] = ACTIONS(1),
    [aux_sym_global_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym__identifier] = ACTIONS(1),
    [sym_error] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_input] = STATE(35),
    [sym_qualified] = STATE(30),
    [sym_global] = STATE(24),
    [sym_local] = STATE(30),
    [sym_interpolation] = STATE(5),
    [sym_raw_marker] = ACTIONS(3),
    [anon_sym_DOT] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym__identifier] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      aux_sym_global_token2,
    ACTIONS(11), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
    STATE(8), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [15] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      aux_sym_global_token2,
    ACTIONS(15), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
    STATE(2), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [30] = 6,
    ACTIONS(19), 1,
      sym_raw_marker,
    ACTIONS(21), 1,
      sym_format_string,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      sym__identifier,
    STATE(12), 1,
      sym_interpolation,
    STATE(31), 1,
      sym_global,
  [49] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      aux_sym_global_token2,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
    STATE(6), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [64] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      aux_sym_global_token2,
    ACTIONS(15), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
    STATE(8), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [79] = 6,
    ACTIONS(19), 1,
      sym_raw_marker,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      sym__identifier,
    ACTIONS(31), 1,
      sym_format_string,
    STATE(12), 1,
      sym_interpolation,
    STATE(32), 1,
      sym_global,
  [98] = 4,
    ACTIONS(35), 1,
      aux_sym_global_token2,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
    STATE(8), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [113] = 5,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      sym__identifier,
    ACTIONS(41), 1,
      sym_raw_marker,
    STATE(12), 1,
      sym_interpolation,
    STATE(34), 1,
      sym_global,
  [129] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      aux_sym_global_token2,
    STATE(11), 2,
      sym_interpolation,
      aux_sym_local_repeat1,
  [143] = 4,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      aux_sym_global_token2,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    STATE(11), 2,
      sym_interpolation,
      aux_sym_local_repeat1,
  [157] = 4,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    ACTIONS(55), 1,
      aux_sym_global_token2,
    STATE(14), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [171] = 4,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      aux_sym_global_token2,
    STATE(15), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [185] = 4,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      aux_sym_global_token2,
    STATE(16), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [199] = 4,
    ACTIONS(11), 1,
      anon_sym_RBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      aux_sym_global_token2,
    STATE(16), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [213] = 4,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(61), 1,
      aux_sym_global_token2,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(16), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [227] = 5,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      sym__identifier,
    ACTIONS(41), 1,
      sym_raw_marker,
    STATE(12), 1,
      sym_interpolation,
    STATE(33), 1,
      sym_global,
  [243] = 3,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_interpolation,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
  [254] = 3,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      aux_sym_global_token2,
    STATE(10), 2,
      sym_interpolation,
      aux_sym_local_repeat1,
  [265] = 1,
    ACTIONS(69), 4,
      ts_builtin_sym_end,
      aux_sym_global_token2,
      anon_sym_DOT,
      anon_sym_LBRACE,
  [272] = 1,
    ACTIONS(71), 4,
      ts_builtin_sym_end,
      aux_sym_global_token2,
      anon_sym_DOT,
      anon_sym_LBRACE,
  [279] = 3,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(73), 1,
      aux_sym_global_token1,
    STATE(13), 1,
      sym_interpolation,
  [289] = 1,
    ACTIONS(71), 3,
      aux_sym_global_token2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [295] = 3,
    ACTIONS(5), 1,
      anon_sym_DOT,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    STATE(28), 1,
      sym_local,
  [305] = 3,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      sym_interpolation,
  [315] = 1,
    ACTIONS(69), 3,
      aux_sym_global_token2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [321] = 3,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      aux_sym_global_token1,
    STATE(3), 1,
      sym_interpolation,
  [331] = 1,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
  [335] = 1,
    ACTIONS(81), 1,
      anon_sym_COLON,
  [339] = 1,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
  [343] = 1,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
  [347] = 1,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
  [351] = 1,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
  [355] = 1,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
  [359] = 1,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
  [363] = 1,
    ACTIONS(93), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 15,
  [SMALL_STATE(4)] = 30,
  [SMALL_STATE(5)] = 49,
  [SMALL_STATE(6)] = 64,
  [SMALL_STATE(7)] = 79,
  [SMALL_STATE(8)] = 98,
  [SMALL_STATE(9)] = 113,
  [SMALL_STATE(10)] = 129,
  [SMALL_STATE(11)] = 143,
  [SMALL_STATE(12)] = 157,
  [SMALL_STATE(13)] = 171,
  [SMALL_STATE(14)] = 185,
  [SMALL_STATE(15)] = 199,
  [SMALL_STATE(16)] = 213,
  [SMALL_STATE(17)] = 227,
  [SMALL_STATE(18)] = 243,
  [SMALL_STATE(19)] = 254,
  [SMALL_STATE(20)] = 265,
  [SMALL_STATE(21)] = 272,
  [SMALL_STATE(22)] = 279,
  [SMALL_STATE(23)] = 289,
  [SMALL_STATE(24)] = 295,
  [SMALL_STATE(25)] = 305,
  [SMALL_STATE(26)] = 315,
  [SMALL_STATE(27)] = 321,
  [SMALL_STATE(28)] = 331,
  [SMALL_STATE(29)] = 335,
  [SMALL_STATE(30)] = 339,
  [SMALL_STATE(31)] = 343,
  [SMALL_STATE(32)] = 347,
  [SMALL_STATE(33)] = 351,
  [SMALL_STATE(34)] = 355,
  [SMALL_STATE(35)] = 359,
  [SMALL_STATE(36)] = 363,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 3, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_local_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_local_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_local_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 5, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [91] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__identifier = 0,
  ts_external_token_error = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__identifier] = sym__identifier,
  [ts_external_token_error] = sym_error,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__identifier] = true,
    [ts_external_token_error] = true,
  },
  [2] = {
    [ts_external_token__identifier] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_rgbasm_identifier_external_scanner_create(void);
void tree_sitter_rgbasm_identifier_external_scanner_destroy(void *);
bool tree_sitter_rgbasm_identifier_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_rgbasm_identifier_external_scanner_serialize(void *, char *);
void tree_sitter_rgbasm_identifier_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rgbasm_identifier(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_rgbasm_identifier_external_scanner_create,
      tree_sitter_rgbasm_identifier_external_scanner_destroy,
      tree_sitter_rgbasm_identifier_external_scanner_scan,
      tree_sitter_rgbasm_identifier_external_scanner_serialize,
      tree_sitter_rgbasm_identifier_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "rgbasm_identifier",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
