/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 50
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 27
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_comment = 2,
  sym_raw_marker = 3,
  aux_sym_global_token1 = 4,
  aux_sym_global_token2 = 5,
  anon_sym_DOT = 6,
  sym_format_string = 7,
  anon_sym_LBRACE = 8,
  anon_sym_COLON = 9,
  anon_sym_RBRACE = 10,
  sym_macro_num_arg = 11,
  sym_macro_uniq = 12,
  anon_sym_BSLASH_LT = 13,
  anon_sym_GT = 14,
  sym__identifier = 15,
  sym_error = 16,
  sym_input = 17,
  sym_qualified = 18,
  sym_global = 19,
  sym_local = 20,
  sym__interpolation = 21,
  sym_variable_interpolation = 22,
  sym_macro_interpolation = 23,
  aux_sym_input_repeat1 = 24,
  aux_sym_global_repeat1 = 25,
  aux_sym_local_repeat1 = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_comment] = "comment",
  [sym_raw_marker] = "raw_marker",
  [aux_sym_global_token1] = "global_token1",
  [aux_sym_global_token2] = "global_token2",
  [anon_sym_DOT] = ".",
  [sym_format_string] = "format_string",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COLON] = ":",
  [anon_sym_RBRACE] = "}",
  [sym_macro_num_arg] = "macro_num_arg",
  [sym_macro_uniq] = "macro_uniq",
  [anon_sym_BSLASH_LT] = "\\<",
  [anon_sym_GT] = ">",
  [sym__identifier] = "_identifier",
  [sym_error] = "error",
  [sym_input] = "input",
  [sym_qualified] = "qualified",
  [sym_global] = "global",
  [sym_local] = "local",
  [sym__interpolation] = "_interpolation",
  [sym_variable_interpolation] = "variable_interpolation",
  [sym_macro_interpolation] = "macro_interpolation",
  [aux_sym_input_repeat1] = "input_repeat1",
  [aux_sym_global_repeat1] = "global_repeat1",
  [aux_sym_local_repeat1] = "local_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_comment] = sym_comment,
  [sym_raw_marker] = sym_raw_marker,
  [aux_sym_global_token1] = aux_sym_global_token1,
  [aux_sym_global_token2] = aux_sym_global_token2,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_format_string] = sym_format_string,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_macro_num_arg] = sym_macro_num_arg,
  [sym_macro_uniq] = sym_macro_uniq,
  [anon_sym_BSLASH_LT] = anon_sym_BSLASH_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym__identifier] = sym__identifier,
  [sym_error] = sym_error,
  [sym_input] = sym_input,
  [sym_qualified] = sym_qualified,
  [sym_global] = sym_global,
  [sym_local] = sym_local,
  [sym__interpolation] = sym__interpolation,
  [sym_variable_interpolation] = sym_variable_interpolation,
  [sym_macro_interpolation] = sym_macro_interpolation,
  [aux_sym_input_repeat1] = aux_sym_input_repeat1,
  [aux_sym_global_repeat1] = aux_sym_global_repeat1,
  [aux_sym_local_repeat1] = aux_sym_local_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_marker] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_global_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_global_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_format_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_macro_num_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_uniq] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_error] = {
    .visible = true,
    .named = true,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified] = {
    .visible = true,
    .named = true,
  },
  [sym_global] = {
    .visible = true,
    .named = true,
  },
  [sym_local] = {
    .visible = true,
    .named = true,
  },
  [sym__interpolation] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_input_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_global_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_local_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 3,
  [12] = 4,
  [13] = 5,
  [14] = 6,
  [15] = 7,
  [16] = 9,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 17,
  [21] = 19,
  [22] = 22,
  [23] = 18,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 24,
  [29] = 29,
  [30] = 29,
  [31] = 26,
  [32] = 25,
  [33] = 27,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 42,
  [46] = 44,
  [47] = 47,
  [48] = 41,
  [49] = 43,
};

static const TSCharacterRange sym_format_string_character_set_4[] = {
  {'.', '.'}, {'0', '9'}, {'X', 'X'}, {'b', 'b'}, {'d', 'd'}, {'f', 'f'}, {'o', 'o'}, {'q', 'q'},
  {'s', 's'}, {'u', 'u'}, {'x', 'x'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '#', 22,
        '.', 26,
        ':', 29,
        ';', 21,
        '>', 34,
        '\\', 10,
        '{', 28,
        '}', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        ' ', 1,
        '#', 23,
        '+', 2,
        '-', 4,
        '.', 7,
        '0', 5,
        '\\', 10,
        'q', 17,
        '{', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if ((set_contains(sym_format_string_character_set_4, 11, lookahead)) &&
          (lookahead < '0' || '9' < lookahead)) ADVANCE(27);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '#', 3,
        '-', 4,
        '.', 7,
        '0', 5,
        'q', 17,
        'X', 27,
        'b', 27,
        'd', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'u', 27,
        'x', 27,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '-', 6,
        '.', 13,
        '0', 8,
        'q', 16,
        'X', 27,
        'b', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'x', 27,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '.', 7,
        '0', 5,
        'q', 17,
        'X', 27,
        'b', 27,
        'd', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'u', 27,
        'x', 27,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '.', 7,
        'q', 17,
        'X', 27,
        'b', 27,
        'd', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'u', 27,
        'x', 27,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '.', 13,
        '0', 8,
        'q', 16,
        'X', 27,
        'b', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'x', 27,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '.', 13,
        'q', 17,
        'X', 27,
        'b', 27,
        'd', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'u', 27,
        'x', 27,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        '.', 13,
        'q', 16,
        'X', 27,
        'b', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'x', 27,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      ADVANCE_MAP(
        '.', 13,
        'q', 16,
        'X', 27,
        'b', 27,
        'd', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'u', 27,
        'x', 27,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '<') ADVANCE(33);
      if (lookahead == '@') ADVANCE(32);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(27);
      if (lookahead == 'q') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == '{') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(18);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_raw_marker);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_raw_marker);
      ADVANCE_MAP(
        '-', 6,
        '.', 13,
        '0', 8,
        'q', 16,
        'X', 27,
        'b', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'x', 27,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_global_token1);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_global_token2);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_format_string);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_macro_num_arg);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_macro_uniq);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_BSLASH_LT);
      if (lookahead == '-') ADVANCE(15);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 18},
  [5] = {.lex_state = 18},
  [6] = {.lex_state = 18},
  [7] = {.lex_state = 18},
  [8] = {.lex_state = 18},
  [9] = {.lex_state = 1, .external_lex_state = 2},
  [10] = {.lex_state = 18},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 1, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 18},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 18},
  [26] = {.lex_state = 18},
  [27] = {.lex_state = 18},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 18},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 11},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 11},
  [34] = {.lex_state = 18},
  [35] = {.lex_state = 18},
  [36] = {.lex_state = 18},
  [37] = {.lex_state = 18},
  [38] = {.lex_state = 18},
  [39] = {.lex_state = 18},
  [40] = {.lex_state = 18},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_raw_marker] = ACTIONS(1),
    [aux_sym_global_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_macro_num_arg] = ACTIONS(1),
    [sym_macro_uniq] = ACTIONS(1),
    [anon_sym_BSLASH_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__identifier] = ACTIONS(1),
    [sym_error] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_input] = STATE(47),
    [sym_qualified] = STATE(37),
    [sym_global] = STATE(34),
    [sym_local] = STATE(37),
    [sym__interpolation] = STATE(3),
    [sym_variable_interpolation] = STATE(3),
    [sym_macro_interpolation] = STATE(3),
    [sym_raw_marker] = ACTIONS(3),
    [anon_sym_DOT] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_macro_num_arg] = ACTIONS(9),
    [sym_macro_uniq] = ACTIONS(9),
    [anon_sym_BSLASH_LT] = ACTIONS(11),
    [sym__identifier] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym_qualified] = STATE(39),
    [sym_global] = STATE(35),
    [sym_local] = STATE(39),
    [sym__interpolation] = STATE(3),
    [sym_variable_interpolation] = STATE(3),
    [sym_macro_interpolation] = STATE(3),
    [sym_comment] = ACTIONS(15),
    [sym_raw_marker] = ACTIONS(3),
    [anon_sym_DOT] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_macro_num_arg] = ACTIONS(9),
    [sym_macro_uniq] = ACTIONS(9),
    [anon_sym_BSLASH_LT] = ACTIONS(11),
    [sym__identifier] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(11), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(19), 1,
      aux_sym_global_token2,
    ACTIONS(21), 1,
      anon_sym_DOT,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(25), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(5), 4,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
      aux_sym_global_repeat1,
  [27] = 7,
    ACTIONS(11), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      aux_sym_global_token2,
    ACTIONS(31), 1,
      anon_sym_DOT,
    ACTIONS(25), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(6), 4,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
      aux_sym_global_repeat1,
  [54] = 7,
    ACTIONS(11), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_DOT,
    ACTIONS(33), 1,
      aux_sym_global_token2,
    ACTIONS(25), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(7), 4,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
      aux_sym_global_repeat1,
  [81] = 7,
    ACTIONS(11), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      aux_sym_global_token2,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(25), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(7), 4,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
      aux_sym_global_repeat1,
  [108] = 7,
    ACTIONS(41), 1,
      aux_sym_global_token2,
    ACTIONS(44), 1,
      anon_sym_DOT,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(39), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(49), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(7), 4,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
      aux_sym_global_repeat1,
  [135] = 6,
    ACTIONS(11), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      aux_sym_global_token2,
    ACTIONS(25), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(10), 4,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
      aux_sym_local_repeat1,
  [159] = 8,
    ACTIONS(59), 1,
      sym_raw_marker,
    ACTIONS(61), 1,
      sym_format_string,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(69), 1,
      sym__identifier,
    STATE(42), 1,
      sym_global,
    ACTIONS(65), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(11), 3,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
  [187] = 6,
    ACTIONS(73), 1,
      aux_sym_global_token2,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(82), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(79), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(10), 4,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
      aux_sym_local_repeat1,
  [211] = 6,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(85), 1,
      aux_sym_global_token2,
    ACTIONS(17), 2,
      anon_sym_RBRACE,
      anon_sym_GT,
    ACTIONS(65), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(13), 4,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
      aux_sym_global_repeat1,
  [235] = 6,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(87), 1,
      aux_sym_global_token2,
    ACTIONS(27), 2,
      anon_sym_RBRACE,
      anon_sym_GT,
    ACTIONS(65), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(14), 4,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
      aux_sym_global_repeat1,
  [259] = 6,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(89), 1,
      aux_sym_global_token2,
    ACTIONS(27), 2,
      anon_sym_RBRACE,
      anon_sym_GT,
    ACTIONS(65), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(15), 4,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
      aux_sym_global_repeat1,
  [283] = 6,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(89), 1,
      aux_sym_global_token2,
    ACTIONS(35), 2,
      anon_sym_RBRACE,
      anon_sym_GT,
    ACTIONS(65), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(15), 4,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
      aux_sym_global_repeat1,
  [307] = 6,
    ACTIONS(91), 1,
      aux_sym_global_token2,
    ACTIONS(94), 1,
      anon_sym_LBRACE,
    ACTIONS(100), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(39), 2,
      anon_sym_RBRACE,
      anon_sym_GT,
    ACTIONS(97), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(15), 4,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
      aux_sym_global_repeat1,
  [331] = 8,
    ACTIONS(59), 1,
      sym_raw_marker,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(69), 1,
      sym__identifier,
    ACTIONS(103), 1,
      sym_format_string,
    STATE(45), 1,
      sym_global,
    ACTIONS(65), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(11), 3,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
  [359] = 7,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(69), 1,
      sym__identifier,
    ACTIONS(105), 1,
      sym_raw_marker,
    STATE(44), 1,
      sym_global,
    ACTIONS(65), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(11), 3,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
  [384] = 6,
    ACTIONS(11), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(21), 1,
      anon_sym_DOT,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(25), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(4), 3,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
  [407] = 7,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(69), 1,
      sym__identifier,
    ACTIONS(105), 1,
      sym_raw_marker,
    STATE(41), 1,
      sym_global,
    ACTIONS(65), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(11), 3,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
  [432] = 7,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(69), 1,
      sym__identifier,
    ACTIONS(105), 1,
      sym_raw_marker,
    STATE(46), 1,
      sym_global,
    ACTIONS(65), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(11), 3,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
  [457] = 7,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(69), 1,
      sym__identifier,
    ACTIONS(105), 1,
      sym_raw_marker,
    STATE(48), 1,
      sym_global,
    ACTIONS(65), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(11), 3,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
  [482] = 5,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(107), 1,
      aux_sym_global_token2,
    ACTIONS(9), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(8), 4,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
      aux_sym_local_repeat1,
  [502] = 5,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(17), 2,
      anon_sym_RBRACE,
      anon_sym_GT,
    ACTIONS(65), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(12), 3,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
  [522] = 5,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(109), 1,
      aux_sym_global_token1,
    ACTIONS(65), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(12), 3,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
  [541] = 2,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(113), 6,
      aux_sym_global_token2,
      anon_sym_DOT,
      anon_sym_LBRACE,
      sym_macro_num_arg,
      sym_macro_uniq,
      anon_sym_BSLASH_LT,
  [554] = 2,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(117), 6,
      aux_sym_global_token2,
      anon_sym_DOT,
      anon_sym_LBRACE,
      sym_macro_num_arg,
      sym_macro_uniq,
      anon_sym_BSLASH_LT,
  [567] = 2,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(121), 6,
      aux_sym_global_token2,
      anon_sym_DOT,
      anon_sym_LBRACE,
      sym_macro_num_arg,
      sym_macro_uniq,
      anon_sym_BSLASH_LT,
  [580] = 5,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(123), 1,
      aux_sym_global_token1,
    ACTIONS(9), 2,
      sym_macro_num_arg,
      sym_macro_uniq,
    STATE(4), 3,
      sym__interpolation,
      sym_variable_interpolation,
      sym_macro_interpolation,
  [599] = 2,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(127), 6,
      aux_sym_global_token2,
      anon_sym_DOT,
      anon_sym_LBRACE,
      sym_macro_num_arg,
      sym_macro_uniq,
      anon_sym_BSLASH_LT,
  [612] = 2,
    ACTIONS(127), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(125), 6,
      aux_sym_global_token2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_macro_num_arg,
      sym_macro_uniq,
      anon_sym_GT,
  [624] = 2,
    ACTIONS(117), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(115), 6,
      aux_sym_global_token2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_macro_num_arg,
      sym_macro_uniq,
      anon_sym_GT,
  [636] = 2,
    ACTIONS(113), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(111), 6,
      aux_sym_global_token2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_macro_num_arg,
      sym_macro_uniq,
      anon_sym_GT,
  [648] = 2,
    ACTIONS(121), 1,
      anon_sym_BSLASH_LT,
    ACTIONS(119), 6,
      aux_sym_global_token2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_macro_num_arg,
      sym_macro_uniq,
      anon_sym_GT,
  [660] = 5,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    ACTIONS(131), 1,
      anon_sym_LF,
    ACTIONS(133), 1,
      anon_sym_DOT,
    STATE(38), 1,
      aux_sym_input_repeat1,
    STATE(40), 1,
      sym_local,
  [676] = 3,
    ACTIONS(133), 1,
      anon_sym_DOT,
    STATE(40), 1,
      sym_local,
    ACTIONS(135), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [687] = 3,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    ACTIONS(137), 1,
      anon_sym_LF,
    STATE(36), 1,
      aux_sym_input_repeat1,
  [697] = 3,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    ACTIONS(131), 1,
      anon_sym_LF,
    STATE(38), 1,
      aux_sym_input_repeat1,
  [707] = 3,
    ACTIONS(131), 1,
      anon_sym_LF,
    ACTIONS(140), 1,
      ts_builtin_sym_end,
    STATE(36), 1,
      aux_sym_input_repeat1,
  [717] = 1,
    ACTIONS(135), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [722] = 1,
    ACTIONS(142), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [727] = 1,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
  [731] = 1,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
  [735] = 1,
    ACTIONS(148), 1,
      anon_sym_COLON,
  [739] = 1,
    ACTIONS(150), 1,
      anon_sym_GT,
  [743] = 1,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
  [747] = 1,
    ACTIONS(154), 1,
      anon_sym_GT,
  [751] = 1,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
  [755] = 1,
    ACTIONS(158), 1,
      anon_sym_RBRACE,
  [759] = 1,
    ACTIONS(160), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 27,
  [SMALL_STATE(5)] = 54,
  [SMALL_STATE(6)] = 81,
  [SMALL_STATE(7)] = 108,
  [SMALL_STATE(8)] = 135,
  [SMALL_STATE(9)] = 159,
  [SMALL_STATE(10)] = 187,
  [SMALL_STATE(11)] = 211,
  [SMALL_STATE(12)] = 235,
  [SMALL_STATE(13)] = 259,
  [SMALL_STATE(14)] = 283,
  [SMALL_STATE(15)] = 307,
  [SMALL_STATE(16)] = 331,
  [SMALL_STATE(17)] = 359,
  [SMALL_STATE(18)] = 384,
  [SMALL_STATE(19)] = 407,
  [SMALL_STATE(20)] = 432,
  [SMALL_STATE(21)] = 457,
  [SMALL_STATE(22)] = 482,
  [SMALL_STATE(23)] = 502,
  [SMALL_STATE(24)] = 522,
  [SMALL_STATE(25)] = 541,
  [SMALL_STATE(26)] = 554,
  [SMALL_STATE(27)] = 567,
  [SMALL_STATE(28)] = 580,
  [SMALL_STATE(29)] = 599,
  [SMALL_STATE(30)] = 612,
  [SMALL_STATE(31)] = 624,
  [SMALL_STATE(32)] = 636,
  [SMALL_STATE(33)] = 648,
  [SMALL_STATE(34)] = 660,
  [SMALL_STATE(35)] = 676,
  [SMALL_STATE(36)] = 687,
  [SMALL_STATE(37)] = 697,
  [SMALL_STATE(38)] = 707,
  [SMALL_STATE(39)] = 717,
  [SMALL_STATE(40)] = 722,
  [SMALL_STATE(41)] = 727,
  [SMALL_STATE(42)] = 731,
  [SMALL_STATE(43)] = 735,
  [SMALL_STATE(44)] = 739,
  [SMALL_STATE(45)] = 743,
  [SMALL_STATE(46)] = 747,
  [SMALL_STATE(47)] = 751,
  [SMALL_STATE(48)] = 755,
  [SMALL_STATE(49)] = 759,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_global, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_global, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 3, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_global, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_local_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_local_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_local_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_local_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_local_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_interpolation, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_interpolation, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_interpolation, 5, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_interpolation, 5, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_interpolation, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_interpolation, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_interpolation, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_interpolation, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [156] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__identifier = 0,
  ts_external_token_error = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__identifier] = sym__identifier,
  [ts_external_token_error] = sym_error,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__identifier] = true,
    [ts_external_token_error] = true,
  },
  [2] = {
    [ts_external_token__identifier] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_rgbasm_identifier_external_scanner_create(void);
void tree_sitter_rgbasm_identifier_external_scanner_destroy(void *);
bool tree_sitter_rgbasm_identifier_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_rgbasm_identifier_external_scanner_serialize(void *, char *);
void tree_sitter_rgbasm_identifier_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rgbasm_identifier(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_rgbasm_identifier_external_scanner_create,
      tree_sitter_rgbasm_identifier_external_scanner_destroy,
      tree_sitter_rgbasm_identifier_external_scanner_scan,
      tree_sitter_rgbasm_identifier_external_scanner_serialize,
      tree_sitter_rgbasm_identifier_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "rgbasm_identifier",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
