/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 50
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_comment = 2,
  sym_raw_marker = 3,
  aux_sym_global_token1 = 4,
  aux_sym_global_token2 = 5,
  anon_sym_DOT = 6,
  sym_format_string = 7,
  sym_uniqueness_affix = 8,
  anon_sym_LBRACE = 9,
  anon_sym_COLON = 10,
  anon_sym_RBRACE = 11,
  sym__identifier = 12,
  sym_error = 13,
  sym_input = 14,
  sym_qualified = 15,
  sym_global = 16,
  sym_local = 17,
  sym_interpolation = 18,
  aux_sym_input_repeat1 = 19,
  aux_sym_global_repeat1 = 20,
  aux_sym_local_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_comment] = "comment",
  [sym_raw_marker] = "raw_marker",
  [aux_sym_global_token1] = "global_token1",
  [aux_sym_global_token2] = "global_token2",
  [anon_sym_DOT] = ".",
  [sym_format_string] = "format_string",
  [sym_uniqueness_affix] = "uniqueness_affix",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COLON] = ":",
  [anon_sym_RBRACE] = "}",
  [sym__identifier] = "_identifier",
  [sym_error] = "error",
  [sym_input] = "input",
  [sym_qualified] = "qualified",
  [sym_global] = "global",
  [sym_local] = "local",
  [sym_interpolation] = "interpolation",
  [aux_sym_input_repeat1] = "input_repeat1",
  [aux_sym_global_repeat1] = "global_repeat1",
  [aux_sym_local_repeat1] = "local_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_comment] = sym_comment,
  [sym_raw_marker] = sym_raw_marker,
  [aux_sym_global_token1] = aux_sym_global_token1,
  [aux_sym_global_token2] = aux_sym_global_token2,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_format_string] = sym_format_string,
  [sym_uniqueness_affix] = sym_uniqueness_affix,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__identifier] = sym__identifier,
  [sym_error] = sym_error,
  [sym_input] = sym_input,
  [sym_qualified] = sym_qualified,
  [sym_global] = sym_global,
  [sym_local] = sym_local,
  [sym_interpolation] = sym_interpolation,
  [aux_sym_input_repeat1] = aux_sym_input_repeat1,
  [aux_sym_global_repeat1] = aux_sym_global_repeat1,
  [aux_sym_local_repeat1] = aux_sym_local_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_marker] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_global_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_global_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_format_string] = {
    .visible = true,
    .named = true,
  },
  [sym_uniqueness_affix] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_error] = {
    .visible = true,
    .named = true,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified] = {
    .visible = true,
    .named = true,
  },
  [sym_global] = {
    .visible = true,
    .named = true,
  },
  [sym_local] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_input_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_global_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_local_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 8,
  [12] = 3,
  [13] = 5,
  [14] = 7,
  [15] = 4,
  [16] = 6,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 19,
  [25] = 25,
  [26] = 17,
  [27] = 20,
  [28] = 23,
  [29] = 22,
  [30] = 21,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 33,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 39,
  [42] = 38,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 46,
  [48] = 43,
  [49] = 45,
};

static const TSCharacterRange sym_format_string_character_set_4[] = {
  {'.', '.'}, {'0', '9'}, {'X', 'X'}, {'b', 'b'}, {'d', 'd'}, {'f', 'f'}, {'o', 'o'}, {'q', 'q'},
  {'s', 's'}, {'u', 'u'}, {'x', 'x'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == ';') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == '{') ADVANCE(29);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        ' ', 1,
        '#', 23,
        '+', 2,
        '-', 4,
        '.', 7,
        '0', 5,
        'q', 16,
        '{', 29,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if ((set_contains(sym_format_string_character_set_4, 11, lookahead)) &&
          (lookahead < '0' || '9' < lookahead)) ADVANCE(27);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '#', 3,
        '-', 4,
        '.', 7,
        '0', 5,
        'q', 16,
        'X', 27,
        'b', 27,
        'd', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'u', 27,
        'x', 27,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '-', 6,
        '.', 12,
        '0', 8,
        'q', 15,
        'X', 27,
        'b', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'x', 27,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '.', 7,
        '0', 5,
        'q', 16,
        'X', 27,
        'b', 27,
        'd', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'u', 27,
        'x', 27,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '.', 7,
        'q', 16,
        'X', 27,
        'b', 27,
        'd', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'u', 27,
        'x', 27,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '.', 12,
        '0', 8,
        'q', 15,
        'X', 27,
        'b', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'x', 27,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '.', 12,
        'q', 16,
        'X', 27,
        'b', 27,
        'd', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'u', 27,
        'x', 27,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        '.', 12,
        'q', 15,
        'X', 27,
        'b', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'x', 27,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      ADVANCE_MAP(
        '.', 12,
        'q', 15,
        'X', 27,
        'b', 27,
        'd', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'u', 27,
        'x', 27,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '@') ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == '{') ADVANCE(29);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(27);
      if (lookahead == 'q') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '{') ADVANCE(29);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 17:
      if (eof) ADVANCE(19);
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == '{') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == ';') ADVANCE(21);
      if (lookahead == '{') ADVANCE(29);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_raw_marker);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_raw_marker);
      ADVANCE_MAP(
        '-', 6,
        '.', 12,
        '0', 8,
        'q', 15,
        'X', 27,
        'b', 27,
        'f', 27,
        'o', 27,
        's', 27,
        'x', 27,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_global_token1);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_global_token2);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_format_string);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_uniqueness_affix);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 17},
  [4] = {.lex_state = 17},
  [5] = {.lex_state = 17},
  [6] = {.lex_state = 17},
  [7] = {.lex_state = 17},
  [8] = {.lex_state = 1, .external_lex_state = 2},
  [9] = {.lex_state = 17},
  [10] = {.lex_state = 17},
  [11] = {.lex_state = 1, .external_lex_state = 2},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 17},
  [18] = {.lex_state = 17},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 17},
  [21] = {.lex_state = 17},
  [22] = {.lex_state = 17},
  [23] = {.lex_state = 17},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 17},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 11},
  [32] = {.lex_state = 17},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 17},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 17},
  [37] = {.lex_state = 17},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 17},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_raw_marker] = ACTIONS(1),
    [aux_sym_global_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_uniqueness_affix] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym__identifier] = ACTIONS(1),
    [sym_error] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_input] = STATE(44),
    [sym_qualified] = STATE(34),
    [sym_global] = STATE(18),
    [sym_local] = STATE(34),
    [sym_interpolation] = STATE(5),
    [sym_raw_marker] = ACTIONS(3),
    [anon_sym_DOT] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym__identifier] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_raw_marker,
    ACTIONS(5), 1,
      anon_sym_DOT,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      sym__identifier,
    ACTIONS(11), 1,
      sym_comment,
    STATE(5), 1,
      sym_interpolation,
    STATE(25), 1,
      sym_global,
    STATE(40), 2,
      sym_qualified,
      sym_local,
  [26] = 5,
    ACTIONS(15), 1,
      aux_sym_global_token2,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(6), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [44] = 5,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      aux_sym_global_token2,
    ACTIONS(13), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(7), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [62] = 5,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      aux_sym_global_token2,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(4), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [80] = 5,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      aux_sym_global_token2,
    ACTIONS(31), 1,
      anon_sym_DOT,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(7), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [98] = 5,
    ACTIONS(35), 1,
      aux_sym_global_token2,
    ACTIONS(38), 1,
      anon_sym_DOT,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(7), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [116] = 6,
    ACTIONS(43), 1,
      sym_raw_marker,
    ACTIONS(45), 1,
      sym_format_string,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      sym__identifier,
    STATE(13), 1,
      sym_interpolation,
    STATE(39), 1,
      sym_global,
  [135] = 4,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(53), 1,
      aux_sym_global_token2,
    ACTIONS(51), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(10), 2,
      sym_interpolation,
      aux_sym_local_repeat1,
  [150] = 4,
    ACTIONS(57), 1,
      aux_sym_global_token2,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(10), 2,
      sym_interpolation,
      aux_sym_local_repeat1,
  [165] = 6,
    ACTIONS(43), 1,
      sym_raw_marker,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      sym__identifier,
    ACTIONS(63), 1,
      sym_format_string,
    STATE(13), 1,
      sym_interpolation,
    STATE(41), 1,
      sym_global,
  [184] = 4,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(65), 1,
      aux_sym_global_token2,
    ACTIONS(13), 2,
      sym_uniqueness_affix,
      anon_sym_RBRACE,
    STATE(16), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [199] = 4,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      aux_sym_global_token2,
    ACTIONS(23), 2,
      sym_uniqueness_affix,
      anon_sym_RBRACE,
    STATE(15), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [214] = 4,
    ACTIONS(69), 1,
      aux_sym_global_token2,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 2,
      sym_uniqueness_affix,
      anon_sym_RBRACE,
    STATE(14), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [229] = 4,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_global_token2,
    ACTIONS(13), 2,
      sym_uniqueness_affix,
      anon_sym_RBRACE,
    STATE(14), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [244] = 4,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_global_token2,
    ACTIONS(29), 2,
      sym_uniqueness_affix,
      anon_sym_RBRACE,
    STATE(14), 2,
      sym_interpolation,
      aux_sym_global_repeat1,
  [259] = 4,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    STATE(3), 1,
      sym_interpolation,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [273] = 5,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      anon_sym_LF,
    ACTIONS(81), 1,
      anon_sym_DOT,
    STATE(32), 1,
      aux_sym_input_repeat1,
    STATE(37), 1,
      sym_local,
  [289] = 5,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      sym__identifier,
    ACTIONS(83), 1,
      sym_raw_marker,
    STATE(13), 1,
      sym_interpolation,
    STATE(38), 1,
      sym_global,
  [305] = 2,
    ACTIONS(85), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(87), 3,
      aux_sym_global_token2,
      anon_sym_DOT,
      anon_sym_LBRACE,
  [315] = 2,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(91), 3,
      aux_sym_global_token2,
      anon_sym_DOT,
      anon_sym_LBRACE,
  [325] = 2,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(95), 3,
      aux_sym_global_token2,
      anon_sym_DOT,
      anon_sym_LBRACE,
  [335] = 2,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(99), 3,
      aux_sym_global_token2,
      anon_sym_DOT,
      anon_sym_LBRACE,
  [345] = 5,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      sym__identifier,
    ACTIONS(83), 1,
      sym_raw_marker,
    STATE(13), 1,
      sym_interpolation,
    STATE(42), 1,
      sym_global,
  [361] = 3,
    ACTIONS(81), 1,
      anon_sym_DOT,
    STATE(37), 1,
      sym_local,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [372] = 3,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym_interpolation,
    ACTIONS(23), 2,
      sym_uniqueness_affix,
      anon_sym_RBRACE,
  [383] = 1,
    ACTIONS(85), 4,
      aux_sym_global_token2,
      sym_uniqueness_affix,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [390] = 1,
    ACTIONS(97), 4,
      aux_sym_global_token2,
      sym_uniqueness_affix,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [397] = 1,
    ACTIONS(93), 4,
      aux_sym_global_token2,
      sym_uniqueness_affix,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [404] = 1,
    ACTIONS(89), 4,
      aux_sym_global_token2,
      sym_uniqueness_affix,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [411] = 3,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      aux_sym_global_token2,
    STATE(9), 2,
      sym_interpolation,
      aux_sym_local_repeat1,
  [422] = 3,
    ACTIONS(79), 1,
      anon_sym_LF,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    STATE(36), 1,
      aux_sym_input_repeat1,
  [432] = 3,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      aux_sym_global_token1,
    STATE(3), 1,
      sym_interpolation,
  [442] = 3,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      anon_sym_LF,
    STATE(32), 1,
      aux_sym_input_repeat1,
  [452] = 3,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(109), 1,
      aux_sym_global_token1,
    STATE(12), 1,
      sym_interpolation,
  [462] = 3,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 1,
      anon_sym_LF,
    STATE(36), 1,
      aux_sym_input_repeat1,
  [472] = 1,
    ACTIONS(114), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [477] = 2,
    ACTIONS(116), 1,
      sym_uniqueness_affix,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
  [484] = 2,
    ACTIONS(120), 1,
      sym_uniqueness_affix,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
  [491] = 1,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [496] = 2,
    ACTIONS(124), 1,
      sym_uniqueness_affix,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
  [503] = 2,
    ACTIONS(128), 1,
      sym_uniqueness_affix,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
  [510] = 1,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
  [514] = 1,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
  [518] = 1,
    ACTIONS(136), 1,
      anon_sym_COLON,
  [522] = 1,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
  [526] = 1,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
  [530] = 1,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
  [534] = 1,
    ACTIONS(144), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 62,
  [SMALL_STATE(6)] = 80,
  [SMALL_STATE(7)] = 98,
  [SMALL_STATE(8)] = 116,
  [SMALL_STATE(9)] = 135,
  [SMALL_STATE(10)] = 150,
  [SMALL_STATE(11)] = 165,
  [SMALL_STATE(12)] = 184,
  [SMALL_STATE(13)] = 199,
  [SMALL_STATE(14)] = 214,
  [SMALL_STATE(15)] = 229,
  [SMALL_STATE(16)] = 244,
  [SMALL_STATE(17)] = 259,
  [SMALL_STATE(18)] = 273,
  [SMALL_STATE(19)] = 289,
  [SMALL_STATE(20)] = 305,
  [SMALL_STATE(21)] = 315,
  [SMALL_STATE(22)] = 325,
  [SMALL_STATE(23)] = 335,
  [SMALL_STATE(24)] = 345,
  [SMALL_STATE(25)] = 361,
  [SMALL_STATE(26)] = 372,
  [SMALL_STATE(27)] = 383,
  [SMALL_STATE(28)] = 390,
  [SMALL_STATE(29)] = 397,
  [SMALL_STATE(30)] = 404,
  [SMALL_STATE(31)] = 411,
  [SMALL_STATE(32)] = 422,
  [SMALL_STATE(33)] = 432,
  [SMALL_STATE(34)] = 442,
  [SMALL_STATE(35)] = 452,
  [SMALL_STATE(36)] = 462,
  [SMALL_STATE(37)] = 472,
  [SMALL_STATE(38)] = 477,
  [SMALL_STATE(39)] = 484,
  [SMALL_STATE(40)] = 491,
  [SMALL_STATE(41)] = 496,
  [SMALL_STATE(42)] = 503,
  [SMALL_STATE(43)] = 510,
  [SMALL_STATE(44)] = 514,
  [SMALL_STATE(45)] = 518,
  [SMALL_STATE(46)] = 522,
  [SMALL_STATE(47)] = 526,
  [SMALL_STATE(48)] = 530,
  [SMALL_STATE(49)] = 534,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_global, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_global, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 3, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_global, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_local_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_local_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_local_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 5, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 5, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 6, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 6, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [134] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__identifier = 0,
  ts_external_token_error = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__identifier] = sym__identifier,
  [ts_external_token_error] = sym_error,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__identifier] = true,
    [ts_external_token_error] = true,
  },
  [2] = {
    [ts_external_token__identifier] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_rgbasm_identifier_external_scanner_create(void);
void tree_sitter_rgbasm_identifier_external_scanner_destroy(void *);
bool tree_sitter_rgbasm_identifier_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_rgbasm_identifier_external_scanner_serialize(void *, char *);
void tree_sitter_rgbasm_identifier_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rgbasm_identifier(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_rgbasm_identifier_external_scanner_create,
      tree_sitter_rgbasm_identifier_external_scanner_destroy,
      tree_sitter_rgbasm_identifier_external_scanner_scan,
      tree_sitter_rgbasm_identifier_external_scanner_serialize,
      tree_sitter_rgbasm_identifier_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "rgbasm_identifier",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
