; ==============================================================================
; Comments
; ==============================================================================

(comment) @comment

; ==============================================================================
; Strings
; ==============================================================================``

((format_string) @string.escape (#set! priority 110))

; ==============================================================================
; Punctuation
; ==============================================================================

((raw_marker) @punctuation.delimiter (#set! priority 110))

(local "." @punctuation.delimiter (#set! priority 110))

(interpolation ["{" "}"] @punctuation.special.interpolatio (#set! priority 110))

(interpolation ":" @punctuation.delimiter (#set! priority 110))

; ==============================================================================
; Identifiers
; ==============================================================================

((global) @variable (#set! priority 110))

(qualified (global) @module (#set! priority 115))

((local) @label (#set! priority 110))

((global) @constant
  (#set! priority 120)
  (#any-of? @constant
    ; WARN: script-generated content. Do not edit directly.
    "ACCLATCH0_START" "ACCLATCH1_FINISH" "AUD1ENVB_DIR" "AUD1ENVF_DIR" "AUD1ENVF_INIT_VOL" "AUD1ENVF_PACE" "AUD1ENV_DIR" "AUD1ENV_DOWN" "AUD1ENV_INIT_VOLUME" "AUD1ENV_PACE" "AUD1ENV_UP" "AUD1HIGHB_LEN_ENABLE" "AUD1HIGHB_RESTART" "AUD1HIGHF_PERIOD_HIGH"
    "AUD1HIGH_LENGTH_OFF" "AUD1HIGH_LENGTH_ON" "AUD1HIGH_PERIOD_HIGH" "AUD1HIGH_RESTART" "AUD1LENF_DUTY" "AUD1LENF_TIMER" "AUD1LEN_DUTY" "AUD1LEN_DUTY_12_5" "AUD1LEN_DUTY_25" "AUD1LEN_DUTY_50" "AUD1LEN_DUTY_75" "AUD1LEN_TIMER" "AUD1RAM" "AUD1SWEEPB_DIR"
    "AUD1SWEEPF_DIR" "AUD1SWEEPF_TIME" "AUD1SWEEP_DIR" "AUD1SWEEP_DOWN" "AUD1SWEEP_SHIFT" "AUD1SWEEP_TIME" "AUD1SWEEP_UP" "AUD2ENVB_DIR" "AUD2ENVF_DIR" "AUD2ENVF_INIT_VOL" "AUD2ENVF_PACE" "AUD2ENV_DIR" "AUD2ENV_DOWN" "AUD2ENV_INIT_VOLUME" "AUD2ENV_PACE"
    "AUD2ENV_UP" "AUD2HIGHB_LEN_ENABLE" "AUD2HIGHB_RESTART" "AUD2HIGHF_PERIOD_HIGH" "AUD2HIGH_LENGTH_OFF" "AUD2HIGH_LENGTH_ON" "AUD2HIGH_PERIOD_HIGH" "AUD2HIGH_RESTART" "AUD2LENF_DUTY" "AUD2LENF_TIMER" "AUD2LEN_DUTY" "AUD2LEN_DUTY_12_5" "AUD2LEN_DUTY_25"
    "AUD2LEN_DUTY_50" "AUD2LEN_DUTY_75" "AUD2LEN_TIMER" "AUD2RAM" "AUD3ENAB_ENABLE" "AUD3ENA_OFF" "AUD3ENA_ON" "AUD3HIGHB_LEN_ENABLE" "AUD3HIGHB_RESTART" "AUD3HIGHF_PERIOD_HIGH" "AUD3HIGH_LENGTH_OFF" "AUD3HIGH_LENGTH_ON" "AUD3HIGH_PERIOD_HIGH"
    "AUD3HIGH_RESTART" "AUD3LEVELF_VOLUME" "AUD3LEVEL_100" "AUD3LEVEL_25" "AUD3LEVEL_50" "AUD3LEVEL_MUTE" "AUD3LEVEL_VOLUME" "AUD3RAM" "AUD3WAVE_SIZE" "AUD4ENVB_DIR" "AUD4ENVF_DIR" "AUD4ENVF_INIT_VOL" "AUD4ENVF_PACE" "AUD4ENV_DIR" "AUD4ENV_DOWN"
    "AUD4ENV_INIT_VOLUME" "AUD4ENV_PACE" "AUD4ENV_UP" "AUD4GOB_LEN_ENABLE" "AUD4GOB_RESTART" "AUD4GO_LENGTH_OFF" "AUD4GO_LENGTH_ON" "AUD4GO_RESTART" "AUD4LENF_TIMER" "AUD4LEN_TIMER" "AUD4POLYB_WIDTH" "AUD4POLYF_DIV" "AUD4POLYF_SHIFT" "AUD4POLY_15STEP"
    "AUD4POLY_7STEP" "AUD4POLY_DIV" "AUD4POLY_SHIFT" "AUD4RAM" "AUDENAB_ENABLE" "AUDENAB_ENABLE_CH1" "AUDENAB_ENABLE_CH2" "AUDENAB_ENABLE_CH3" "AUDENAB_ENABLE_CH4" "AUDENAF_CH1_OFF" "AUDENAF_CH1_ON" "AUDENAF_CH2_OFF" "AUDENAF_CH2_ON" "AUDENAF_CH3_OFF"
    "AUDENAF_CH3_ON" "AUDENAF_CH4_OFF" "AUDENAF_CH4_ON" "AUDENA_CH1_OFF" "AUDENA_CH1_ON" "AUDENA_CH2_OFF" "AUDENA_CH2_ON" "AUDENA_CH3_OFF" "AUDENA_CH3_ON" "AUDENA_CH4_OFF" "AUDENA_CH4_ON" "AUDENA_OFF" "AUDENA_ON" "AUDENVB_DIR" "AUDENVF_DIR"
    "AUDENVF_INIT_VOL" "AUDENVF_PACE" "AUDENV_DOWN" "AUDENV_UP" "AUDHIGHB_LEN_ENABLE" "AUDHIGHB_RESTART" "AUDHIGHF_PERIOD_HIGH" "AUDHIGH_LENGTH_OFF" "AUDHIGH_LENGTH_ON" "AUDHIGH_RESTART" "AUDLENF_DUTY" "AUDLENF_TIMER" "AUDLEN_DUTY_12_5" "AUDLEN_DUTY_25"
    "AUDLEN_DUTY_50" "AUDLEN_DUTY_75" "AUDRAM_SIZE" "AUDTERMB_1_LEFT" "AUDTERMB_1_RIGHT" "AUDTERMB_2_LEFT" "AUDTERMB_2_RIGHT" "AUDTERMB_3_LEFT" "AUDTERMB_3_RIGHT" "AUDTERMB_4_LEFT" "AUDTERMB_4_RIGHT" "AUDTERM_1_LEFT" "AUDTERM_1_RIGHT" "AUDTERM_2_LEFT"
    "AUDTERM_2_RIGHT" "AUDTERM_3_LEFT" "AUDTERM_3_RIGHT" "AUDTERM_4_LEFT" "AUDTERM_4_RIGHT" "AUDVOLB_VIN_LEFT" "AUDVOLB_VIN_RIGHT" "AUDVOLF_LEFT" "AUDVOLF_RIGHT" "AUDVOL_LEFT" "AUDVOL_RIGHT" "AUDVOL_VIN_LEFT" "AUDVOL_VIN_RIGHT" "BANKB_ON" "BANKF_OFF"
    "BANKF_ON" "BANK_OFF" "BANK_ON" "BCPSB_AUTOINC" "BCPSF_AUTOINC" "BGPIB_AUTOINC" "BGPIF_AUTOINC" "BGPIF_INDEX" "BGPI_AUTOINC" "BGPI_INDEX" "BGP_SGB_TRANSFER" "BG_BANK0" "BG_BANK1" "BG_PALETTE" "BG_PRIO" "BG_XFLIP" "BG_YFLIP" "BMODE_ADVANCED"
    "BMODE_SIMPLE" "BOOTUPB_B_AGB" "BOOTUP_A_CGB" "BOOTUP_A_DMG" "BOOTUP_A_MGB" "BOOTUP_A_SGB" "BOOTUP_A_SGB2" "BOOTUP_B_AGB" "BOOTUP_B_CGB" "BOOTUP_C_CGB" "BOOTUP_C_DMG" "BOOTUP_C_SGB" "BOOTUP_D_COLOR" "BOOTUP_D_MONO" "BOOTUP_E_CGB"
    "BOOTUP_E_CGB_DMGMODE" "BOOTUP_E_DMG" "BOOTUP_E_DMG0" "BOOTUP_E_SGB" "B_AUD1ENV_DIR" "B_AUD1HIGH_LEN_ENABLE" "B_AUD1HIGH_RESTART" "B_AUD1SWEEP_DIR" "B_AUD2ENV_DIR" "B_AUD2HIGH_LEN_ENABLE" "B_AUD2HIGH_RESTART" "B_AUD3ENA_ENABLE" "B_AUD3HIGH_LEN_ENABLE"
    "B_AUD3HIGH_RESTART" "B_AUD4ENV_DIR" "B_AUD4GO_LEN_ENABLE" "B_AUD4GO_RESTART" "B_AUD4POLY_WIDTH" "B_AUDENA_ENABLE" "B_AUDENA_ENABLE_CH1" "B_AUDENA_ENABLE_CH2" "B_AUDENA_ENABLE_CH3" "B_AUDENA_ENABLE_CH4" "B_AUDTERM_1_LEFT" "B_AUDTERM_1_RIGHT"
    "B_AUDTERM_2_LEFT" "B_AUDTERM_2_RIGHT" "B_AUDTERM_3_LEFT" "B_AUDTERM_3_RIGHT" "B_AUDTERM_4_LEFT" "B_AUDTERM_4_RIGHT" "B_AUDVOL_VIN_LEFT" "B_AUDVOL_VIN_RIGHT" "B_BANK_ON" "B_BGPI_AUTOINC" "B_BG_BANK1" "B_BG_PRIO" "B_BG_XFLIP" "B_BG_YFLIP"
    "B_BOOTUP_B_AGB" "B_COLOR_BLUE" "B_COLOR_GREEN" "B_COLOR_RED" "B_IE_JOYPAD" "B_IE_SERIAL" "B_IE_STAT" "B_IE_TIMER" "B_IE_VBLANK" "B_IF_JOYPAD" "B_IF_SERIAL" "B_IF_STAT" "B_IF_TIMER" "B_IF_VBLANK" "B_JOYP_A" "B_JOYP_B" "B_JOYP_DOWN"
    "B_JOYP_GET_BUTTONS" "B_JOYP_GET_CTRL_PAD" "B_JOYP_LEFT" "B_JOYP_RIGHT" "B_JOYP_SELECT" "B_JOYP_SGB_ONE" "B_JOYP_SGB_ZERO" "B_JOYP_START" "B_JOYP_UP" "B_LCDC_BG" "B_LCDC_BG_MAP" "B_LCDC_BLOCKS" "B_LCDC_ENABLE" "B_LCDC_OBJS" "B_LCDC_OBJ_SIZE"
    "B_LCDC_PRIO" "B_LCDC_WINDOW" "B_LCDC_WIN_MAP" "B_OAM_BANK1" "B_OAM_PAL1" "B_OAM_PRIO" "B_OAM_XFLIP" "B_OAM_YFLIP" "B_OBPI_AUTOINC" "B_OPRI_PRIORITY" "B_PAD_A" "B_PAD_B" "B_PAD_DOWN" "B_PAD_LEFT" "B_PAD_RIGHT" "B_PAD_SELECT" "B_PAD_START"
    "B_PAD_SWAP_A" "B_PAD_SWAP_B" "B_PAD_SWAP_DOWN" "B_PAD_SWAP_LEFT" "B_PAD_SWAP_RIGHT" "B_PAD_SWAP_SELECT" "B_PAD_SWAP_START" "B_PAD_SWAP_UP" "B_PAD_UP" "B_RAMB_RTC_DH_CARRY" "B_RAMB_RTC_DH_HALT" "B_RAMB_RTC_DH_HIGH" "B_RAMB_RUMBLE" "B_RP_DATA_IN"
    "B_RP_LED_ON" "B_SC_SOURCE" "B_SC_SPEED" "B_SC_START" "B_SPD_DOUBLE" "B_SPD_PREPARE" "B_STAT_BUSY" "B_STAT_LYC" "B_STAT_LYCF" "B_STAT_MODE_0" "B_STAT_MODE_1" "B_STAT_MODE_2" "B_TAC_START" "B_VDMA_LEN_BUSY" "B_VDMA_LEN_MODE" "CARTB_RUMBLE_ON"
    "CARTF_RUMBLE_ON" "CART_COMPATIBLE_DMG" "CART_COMPATIBLE_DMG_GBC" "CART_COMPATIBLE_GBC" "CART_DEST_JAPANESE" "CART_DEST_NON_JAPANESE" "CART_INDICATOR_GB" "CART_INDICATOR_SGB" "CART_ROM" "CART_ROM_1024KB" "CART_ROM_1152KB" "CART_ROM_1280KB"
    "CART_ROM_128KB" "CART_ROM_1536KB" "CART_ROM_2048KB" "CART_ROM_256KB" "CART_ROM_32KB" "CART_ROM_4096KB" "CART_ROM_512KB" "CART_ROM_64KB" "CART_ROM_8192KB" "CART_ROM_BANDAI_TAMA5" "CART_ROM_HUDSON_HUC1" "CART_ROM_HUDSON_HUC3" "CART_ROM_MBC1"
    "CART_ROM_MBC1_RAM" "CART_ROM_MBC1_RAM_BAT" "CART_ROM_MBC2" "CART_ROM_MBC2_BAT" "CART_ROM_MBC3" "CART_ROM_MBC3_BAT_RTC" "CART_ROM_MBC3_RAM" "CART_ROM_MBC3_RAM_BAT" "CART_ROM_MBC3_RAM_BAT_RTC" "CART_ROM_MBC5" "CART_ROM_MBC5_RAM" "CART_ROM_MBC5_RAM_BAT"
    "CART_ROM_MBC5_RAM_BAT_RUMBLE" "CART_ROM_MBC5_RAM_RUMBLE" "CART_ROM_MBC5_RUMBLE" "CART_ROM_MBC7_RAM_BAT_GYRO" "CART_ROM_MMM01" "CART_ROM_MMM01_RAM" "CART_ROM_MMM01_RAM_BAT" "CART_ROM_POCKET_CAMERA" "CART_ROM_RAM" "CART_ROM_RAM_BAT" "CART_RUMBLE_OFF"
    "CART_RUMBLE_ON" "CART_SRAM_128KB" "CART_SRAM_2KB" "CART_SRAM_32KB" "CART_SRAM_8KB" "CART_SRAM_DISABLE" "CART_SRAM_ENABLE" "CART_SRAM_NONE" "COLORF_BLUE" "COLORF_GREEN_HIGH" "COLORF_GREEN_LOW" "COLORF_RED" "COLOR_B" "COLOR_BLUE" "COLOR_CH_MAX"
    "COLOR_CH_WIDTH" "COLOR_GREEN_HIGH" "COLOR_GREEN_LOW" "COLOR_RED" "COLOR_SIZE" "HARDWARE_COMPAT_INC" "HARDWARE_INC" "HARDWARE_INC_VERSION" "HDMA5B_MODE" "HDMA5F_BUSY" "HDMA5F_MODE_GP" "HDMA5F_MODE_HBL" "IEB_HILO" "IEB_JOYPAD" "IEB_SERIAL" "IEB_STAT"
    "IEB_TIMER" "IEB_VBLANK" "IEF_HILO" "IEF_JOYPAD" "IEF_LCDC" "IEF_SERIAL" "IEF_STAT" "IEF_TIMER" "IEF_VBLANK" "IE_JOYPAD" "IE_SERIAL" "IE_STAT" "IE_TIMER" "IE_VBLANK" "IFB_JOYPAD" "IFB_SERIAL" "IFB_STAT" "IFB_TIMER" "IFB_VBLANK" "IFF_JOYPAD"
    "IFF_SERIAL" "IFF_STAT" "IFF_TIMER" "IFF_VBLANK" "IF_JOYPAD" "IF_SERIAL" "IF_STAT" "IF_TIMER" "IF_VBLANK" "INT_HANDLER_JOYPAD" "INT_HANDLER_SERIAL" "INT_HANDLER_STAT" "INT_HANDLER_TIMER" "INT_HANDLER_VBLANK" "IR_LED_OFF" "IR_LED_ON" "JOYPB_A"
    "JOYPB_B" "JOYPB_DOWN" "JOYPB_GET_BTN" "JOYPB_GET_DPAD" "JOYPB_LEFT" "JOYPB_RIGHT" "JOYPB_SELECT" "JOYPB_START" "JOYPB_UP" "JOYPF_A" "JOYPF_B" "JOYPF_DOWN" "JOYPF_GET" "JOYPF_INPUTS" "JOYPF_LEFT" "JOYPF_RIGHT" "JOYPF_SELECT" "JOYPF_START" "JOYPF_UP"
    "JOYP_A" "JOYP_B" "JOYP_DOWN" "JOYP_GET" "JOYP_GET_BTN" "JOYP_GET_BUTTONS" "JOYP_GET_CTRL_PAD" "JOYP_GET_DPAD" "JOYP_GET_NONE" "JOYP_INPUTS" "JOYP_LEFT" "JOYP_RIGHT" "JOYP_SELECT" "JOYP_SGB_FINISH" "JOYP_SGB_ONE" "JOYP_SGB_START" "JOYP_SGB_ZERO"
    "JOYP_START" "JOYP_UP" "KEY0F_CGB" "KEY0F_DMG" "KEY0F_MODE" "KEY0F_PGB1" "KEY0F_PGB2" "KEY1F_DBLSPEED" "KEY1F_PREPARE" "LCDCB_BG8000" "LCDCB_BG9C00" "LCDCB_BGON" "LCDCB_BLKS" "LCDCB_OBJ16" "LCDCB_OBJON" "LCDCB_ON" "LCDCB_PRION" "LCDCB_WIN9C00"
    "LCDCB_WINON" "LCDCF_BG8000" "LCDCF_BG8800" "LCDCF_BG9800" "LCDCF_BG9C00" "LCDCF_BGOFF" "LCDCF_BGON" "LCDCF_BLK01" "LCDCF_BLK21" "LCDCF_BLKS" "LCDCF_OBJ16" "LCDCF_OBJ8" "LCDCF_OBJOFF" "LCDCF_OBJON" "LCDCF_OFF" "LCDCF_ON" "LCDCF_PRIOFF" "LCDCF_PRION"
    "LCDCF_WIN9800" "LCDCF_WIN9C00" "LCDCF_WINOFF" "LCDCF_WINON" "LCDC_BG" "LCDC_BG_9800" "LCDC_BG_9C00" "LCDC_BG_MAP" "LCDC_BG_OFF" "LCDC_BG_ON" "LCDC_BLOCK01" "LCDC_BLOCK21" "LCDC_BLOCKS" "LCDC_ENABLE" "LCDC_OBJS" "LCDC_OBJ_16" "LCDC_OBJ_8"
    "LCDC_OBJ_OFF" "LCDC_OBJ_ON" "LCDC_OBJ_SIZE" "LCDC_OFF" "LCDC_ON" "LCDC_PRIO" "LCDC_PRIO_OFF" "LCDC_PRIO_ON" "LCDC_WINDOW" "LCDC_WIN_9800" "LCDC_WIN_9C00" "LCDC_WIN_MAP" "LCDC_WIN_OFF" "LCDC_WIN_ON" "LY_VBLANK" "OAMA_FLAGS" "OAMA_TILEID" "OAMA_X"
    "OAMA_Y" "OAMB_BANK1" "OAMB_PAL1" "OAMB_PRI" "OAMB_XFLIP" "OAMB_YFLIP" "OAMF_BANK0" "OAMF_BANK1" "OAMF_PAL0" "OAMF_PAL1" "OAMF_PALMASK" "OAMF_PRI" "OAMF_XFLIP" "OAMF_YFLIP" "OAM_B" "OAM_BANK0" "OAM_BANK1" "OAM_COUNT" "OAM_PAL0" "OAM_PAL1"
    "OAM_PALETTE" "OAM_PRIO" "OAM_SIZE" "OAM_XFLIP" "OAM_X_OFS" "OAM_YFLIP" "OAM_Y_OFS" "OBJ_B" "OBJ_SIZE" "OBPIB_AUTOINC" "OBPIF_AUTOINC" "OBPIF_INDEX" "OBPI_AUTOINC" "OBPI_INDEX" "OCPSB_AUTOINC" "OCPSF_AUTOINC" "OPRIB_PRI" "OPRIF_PRI" "OPRI_COORD"
    "OPRI_OAM" "OPRI_PRIORITY" "P1F_0" "P1F_1" "P1F_2" "P1F_3" "P1F_4" "P1F_5" "P1F_GET_BTN" "P1F_GET_DPAD" "P1F_GET_NONE" "PADB_A" "PADB_B" "PADB_DOWN" "PADB_LEFT" "PADB_RIGHT" "PADB_SELECT" "PADB_START" "PADB_SWAP_A" "PADB_SWAP_B" "PADB_SWAP_DOWN"
    "PADB_SWAP_LEFT" "PADB_SWAP_RIGHT" "PADB_SWAP_SELECT" "PADB_SWAP_START" "PADB_SWAP_UP" "PADB_UP" "PADF_A" "PADF_B" "PADF_DOWN" "PADF_LEFT" "PADF_RIGHT" "PADF_SELECT" "PADF_START" "PADF_SWAP_A" "PADF_SWAP_B" "PADF_SWAP_DOWN" "PADF_SWAP_LEFT"
    "PADF_SWAP_RIGHT" "PADF_SWAP_SELECT" "PADF_SWAP_START" "PADF_SWAP_UP" "PADF_UP" "PAD_A" "PAD_B" "PAD_BUTTONS" "PAD_CTRL_PAD" "PAD_DOWN" "PAD_LEFT" "PAD_RIGHT" "PAD_SELECT" "PAD_START" "PAD_SWAP_A" "PAD_SWAP_B" "PAD_SWAP_BUTTONS" "PAD_SWAP_CTRL_PAD"
    "PAD_SWAP_DOWN" "PAD_SWAP_LEFT" "PAD_SWAP_RIGHT" "PAD_SWAP_SELECT" "PAD_SWAP_START" "PAD_SWAP_UP" "PAD_UP" "PAL_B" "PAL_COLORS" "PAL_SIZE" "PCM12F_CH1" "PCM12F_CH2" "PCM12_CH1" "PCM12_CH2" "PCM34F_CH3" "PCM34F_CH4" "PCM34_CH3" "PCM34_CH4"
    "RAMB_RTC_DH" "RAMB_RTC_DH_CARRY" "RAMB_RTC_DH_HALT" "RAMB_RTC_DH_HIGH" "RAMB_RTC_DL" "RAMB_RTC_H" "RAMB_RTC_M" "RAMB_RTC_S" "RAMB_RUMBLE" "RAMB_RUMBLE_OFF" "RAMB_RUMBLE_ON" "RAMG_CART_RAM" "RAMG_CART_RAM_RO" "RAMG_IR" "RAMG_RTC_IN" "RAMG_RTC_IN_ARG"
    "RAMG_RTC_IN_CMD" "RAMG_RTC_OUT" "RAMG_RTC_OUT_CMD" "RAMG_RTC_OUT_RESULT" "RAMG_RTC_SEMAPHORE" "RAMG_SRAM_DISABLE" "RAMG_SRAM_ENABLE" "RAMREG_ENABLE" "RPB_DATAIN" "RPB_LED_ON" "RPF_DATAIN" "RPF_DISREAD" "RPF_ENREAD" "RPF_LED_ON" "RPF_READ"
    "RPF_WRITE_HI" "RPF_WRITE_LO" "RP_DATA_IN" "RP_DISABLE" "RP_ENABLE" "RP_LED_ON" "RP_READ" "RP_WRITE_HIGH" "RP_WRITE_LOW" "RTCLATCH_FINISH" "RTCLATCH_START" "RTC_DH" "RTC_DHB_CARRY" "RTC_DHB_HALT" "RTC_DHB_HIGH" "RTC_DHF_CARRY" "RTC_DHF_HALT"
    "RTC_DHF_HIGH" "RTC_DL" "RTC_H" "RTC_M" "RTC_S" "SCB_SOURCE" "SCB_SPEED" "SCB_START" "SCF_SOURCE" "SCF_SPEED" "SCF_START" "SCREEN_AREA" "SCREEN_HEIGHT" "SCREEN_HEIGHT_PX" "SCREEN_WIDTH" "SCREEN_WIDTH_PX" "SCRN_B" "SCRN_VX" "SCRN_VX_B" "SCRN_VY"
    "SCRN_VY_B" "SCRN_V_B" "SCRN_X" "SCRN_X_B" "SCRN_Y" "SCRN_Y_B" "SC_EXTERNAL" "SC_FAST" "SC_INTERNAL" "SC_SLOW" "SC_SOURCE" "SC_SPEED" "SC_START" "SHADE_BLACK" "SHADE_DARK" "SHADE_LIGHT" "SHADE_WHITE" "SPDB_DBLSPEED" "SPDB_PREPARE" "SPDF_DBLSPEED"
    "SPDF_PREPARE" "SPD_DOUBLE" "SPD_PREPARE" "SPD_SINGLE" "STATB_BUSY" "STATB_LYC" "STATB_LYCF" "STATB_MODE00" "STATB_MODE01" "STATB_MODE10" "STATF_BUSY" "STATF_HBL" "STATF_LCD" "STATF_LYC" "STATF_LYCF" "STATF_MODE" "STATF_MODE00" "STATF_MODE01"
    "STATF_MODE10" "STATF_OAM" "STATF_VBL" "STAT_BUSY" "STAT_HBLANK" "STAT_LCD" "STAT_LYC" "STAT_LYCF" "STAT_MODE" "STAT_MODE_0" "STAT_MODE_1" "STAT_MODE_2" "STAT_OAM" "STAT_VBLANK" "SYSF_CGB" "SYSF_DMG" "SYSF_MODE" "SYSF_PGB1" "SYSF_PGB2" "SYS_CGB"
    "SYS_DMG" "SYS_MODE" "SYS_PGB1" "SYS_PGB2" "TACB_START" "TACF_16KHZ" "TACF_262KHZ" "TACF_4KHZ" "TACF_65KHZ" "TACF_CLOCK" "TACF_START" "TACF_STOP" "TAC_16KHZ" "TAC_262KHZ" "TAC_4KHZ" "TAC_65KHZ" "TAC_CLOCK" "TAC_START" "TAC_STOP" "TILEMAP0" "TILEMAP1"
    "TILEMAP_AREA" "TILEMAP_HEIGHT" "TILEMAP_HEIGHT_PX" "TILEMAP_WIDTH" "TILEMAP_WIDTH_PX" "TILE_B" "TILE_HEIGHT" "TILE_SIZE" "TILE_WIDTH" "TILE_X" "TILE_Y" "VBK_BANK" "VDMA_LENB_BUSY" "VDMA_LENB_MODE" "VDMA_LENB_SIZE" "VDMA_LENF_BUSY" "VDMA_LENF_MODE"
    "VDMA_LENF_MODE_GP" "VDMA_LENF_MODE_HBL" "VDMA_LENF_NO" "VDMA_LENF_YES" "VDMA_LEN_BUSY" "VDMA_LEN_MODE" "VDMA_LEN_MODE_GENERAL" "VDMA_LEN_MODE_HBLANK" "VDMA_LEN_NO" "VDMA_LEN_SIZE" "VDMA_LEN_YES" "WBKF_BANK" "WBK_BANK" "WX_OFS" "_AUD3WAVERAM" "_HRAM"
    "_IO" "_OAMRAM" "_RAM" "_RAMBANK" "_ROM" "_ROMBANK" "_SCRN0" "_SCRN1" "_SRAM" "_VRAM" "_VRAM8000" "_VRAM8800" "_VRAM9000" "rACCELX0" "rACCELX1" "rACCELY0" "rACCELY1" "rACCLATCH0" "rACCLATCH1" "rAUD1ENV" "rAUD1HIGH" "rAUD1LEN" "rAUD1LOW" "rAUD1SWEEP"
    "rAUD2ENV" "rAUD2HIGH" "rAUD2LEN" "rAUD2LOW" "rAUD3ENA" "rAUD3HIGH" "rAUD3LEN" "rAUD3LEVEL" "rAUD3LOW" "rAUD3WAVE_0" "rAUD3WAVE_1" "rAUD3WAVE_2" "rAUD3WAVE_3" "rAUD3WAVE_4" "rAUD3WAVE_5" "rAUD3WAVE_6" "rAUD3WAVE_7" "rAUD3WAVE_8" "rAUD3WAVE_9"
    "rAUD3WAVE_A" "rAUD3WAVE_B" "rAUD3WAVE_C" "rAUD3WAVE_D" "rAUD3WAVE_E" "rAUD3WAVE_F" "rAUD4ENV" "rAUD4GO" "rAUD4LEN" "rAUD4POLY" "rAUDENA" "rAUDTERM" "rAUDVOL" "rBANK" "rBCPD" "rBCPS" "rBGP" "rBGPD" "rBGPI" "rBMODE" "rDIV" "rDMA" "rEEPROM" "rFLASH"
    "rFLASHA" "rFLASHB" "rFMODE" "rHDMA1" "rHDMA2" "rHDMA3" "rHDMA4" "rHDMA5" "rIE" "rIF" "rIRREG" "rJOYP" "rKEY0" "rKEY1" "rLCDC" "rLY" "rLYC" "rNR10" "rNR11" "rNR12" "rNR13" "rNR14" "rNR21" "rNR22" "rNR23" "rNR24" "rNR30" "rNR31" "rNR32" "rNR33" "rNR34"
    "rNR41" "rNR42" "rNR43" "rNR44" "rNR50" "rNR51" "rNR52" "rOBP0" "rOBP1" "rOBPD" "rOBPI" "rOCPD" "rOCPS" "rOPRI" "rP1" "rPCM12" "rPCM34" "rRAMB" "rRAMBA" "rRAMBB" "rRAMG" "rRAMREG" "rROM2B" "rROMB" "rROMB0" "rROMB1" "rROMBA" "rROMBB" "rRP" "rRTCLATCH"
    "rRTCREG" "rSB" "rSC" "rSCX" "rSCY" "rSMBK" "rSPD" "rSTAT" "rSVBK" "rSYS" "rTAC" "rTIMA" "rTMA" "rVBK" "rVDMA_DEST_HIGH" "rVDMA_DEST_LOW" "rVDMA_LEN" "rVDMA_SRC_HIGH" "rVDMA_SRC_LOW" "rWBK" "rWX" "rWY"
    ; END WARN
    ))
